Library/Library/Models/Loan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Models
{
    public class Loan
    {
        public int Id { get; set; }
        public Book Book { get; set; }
        public User User { get; set; }
        public DateTime LoanDate { get; set; }
        public DateTime DateReturned { get; set; }
        public LoanStatusEnum Status { get; set; }
        public int FinePaid { get; set; }

        public Loan(int id, Book book, User user, DateTime loanDate)
        {
            Id = id;
            Book = book;
            User = user;
            LoanDate = loanDate;
            Status = LoanStatusEnum.Active;
        }

        public Loan()
        {

        }
    }
}

Library/Library/ViewModels/LoanViewModel.cs
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Library.ViewModels
{
    public class LoanViewModel
    {
        public List<SelectListItem> Books { get; set; }
        public string SelectedBook { get; set; }

        public LoanViewModel()
        {
            Books = new List<SelectListItem>();

            foreach (var book in Storage.Books)
            {
                Books.Add(new SelectListItem
                {
                    Text = book.Name,
                    Value = book.Id.ToString()
                });
            }
        }
    }
}

Library/Library/Controllers/LoanController.cs
using Library.Models;
using Library.Services;
using Library.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Library.Controllers
{
    public class LoanController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBookService _bookService;
        private readonly ILoanService _loanService;
        public LoanController(IUserService userService,IBookService bookService, ILoanService loanService)
        {
            _userService = userService;
            _bookService = bookService;
            _loanService = loanService;
        }

        public IActionResult Index()
        {
            var loans = new LoanListViewModel();
            return View(loans);
        }

        [HttpGet]
        public IActionResult LoanBooks()
        {
            var loan = new LoanViewModel();
            return View(loan);
        }

        [HttpPost]
        public IActionResult LoanBooks(LoanViewModel model)
        {
            var bookIsAvailable = _loanService.CheckIfBookIsAvailable(model.SelectedBook);
            var userHasTheBook = _loanService.CheckIfUserHasTheBook(model.SelectedBook);
            var moreThan3 = _loanService.LoanedMoreThan3();
            if (!bookIsAvailable)
            {
                ModelState.AddModelError("CustomError", "The book isn't available.");
                return View(model);

            }else if (userHasTheBook)
            {
                ModelState.AddModelError("CustomError", "You have already loaned the book .");
                return View(model);
            }else if (moreThan3)
            {
                ModelState.AddModelError("CustomError", "You have already loaned 3 books, can't have more ");
                return View(model);
            }
            _loanService.CreateLoan(model);
            return RedirectToAction("LogIn", "User");
        }

        [HttpGet]
        public IActionResult ReturnBook(int id)
        {
            _loanService.ReturnBook(id);
            return RedirectToAction("LogIn", "User");
        }

    }
}

Library/Library/Views/Loan/Index.cshtml
@model  BookLibrary.ViewModels.LoanListViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Loans</h2>
<br>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Book</th>
            <th>UserName</th>
            <th>Date Loaned</th>
            <th>Date Returned</th>
            <th>Status</th>
            <th>Fine Paid</th>
        </tr>
    </thead>
    <tbody>
        @{ 
            foreach (var loan in Model.AllLoans)
            {
                <tr>
                    <td>@loan.Id</td>
                    <td>@loan.Book.Name</td>
                    <td>@loan.User.Email</td>
                    <td>@loan.LoanDate</td>
                    <td>@loan.DateReturned</td>
                    <td>@loan.Status</td>
                    <td>@loan.FinePaid</td>
                </tr>
            }
        }
    </tbody>
</table>

Library/Library/Views/Loan/LoanBooks.cshtml
@model BookLibrary.ViewModels.LoanViewModel
@{
    ViewData["Title"] = "LoanBooks";
}

<h2>Select Book</h2>
<div class="container">
    <form asp-action="LoanBooks" asp-controller="Loan">
        <select asp-for="SelectedBook" asp-items="@Model.Books">
            <option disabled selected>Please select book</option>
        </select>
        <input type="submit" value="Loan" class="btn btn-primary" />
    </form>
    <a class="btn btn-danger" asp-action="LogIn" asp-controller="User">Back</a>
</div>
@Html.ValidationMessage("CustomError", new { @class = "text-danger" })